server: "internal"

containers:
  - sustainable_steps-front-1
  - vaultwarden
  - farm_wiki-nginx-1
  - pihole

alert_email: "jens@farmurban.co.uk"
from_email: "jens@farmurban.co.uk"
delegated_user: "jens@farmurban.co.uk"

service_account_file: "service_account.json"
state_file: "container_status.json"

docker_timeout: 10 # seconds
