services:
  container-monitor:
    # image: container-monitor:latest
    image: ghcr.io/farm-urban/container-monitor:latest
    build: .
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./status:/app/status
      - ./config.yaml:/app/config.yaml:ro
      - ./service_account.json:/app/service_account.json:ro
